//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentation.JobBoardList
{


    public partial class FavoritesJobs
    {

        /// <summary>
        /// Control MainContent.
        /// </summary>
        protected global::System.Web.UI.WebControls.Content MainContent;

        /// <summary>
        /// Control rptFavoritos.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptFavoritos;
    }
}
